apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: ai-recruiter
    component: ai-recruiter
  name: ai-recruiter
spec:
  progressDeadlineSeconds: 2147483647
  replicas: 1
  revisionHistoryLimit: 2147483647
  selector:
    matchLabels:
      app: ai-recruiter
      component: ai-recruiter
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: ai-recruiter
        component: ai-recruiter
    spec:
      containers:
      - env:
        - name: DB_URL
          value: ai-recruiter.c1dbtcto26dr.eu-north-1.rds.amazonaws.com
        - name: DB_USERNAME
          value: postgres
        - name: DB_PASSWORD
          value: 4rHxJ621YQIDeNoaZkjM
        - name: DB_NAME
          value: ai-recruiter-prod
        image: 076673840239.dkr.ecr.eu-north-1.amazonaws.com/ai-recruiter
        imagePullPolicy: Always
        name: ai-recruiter
        ports:
        - containerPort: 3000
          name: ai-recruiter
          protocol: TCP
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
