default: &default
  adapter: postgresql
  encoding: unicode
  # For details on connection pooling, see Rails configuration guide
  # https://guides.rubyonrails.org/configuring.html#database-pooling
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: etl_job_manager_development
  host: localhost
  username: postgres

test:
  <<: *default
  database: etl_job_manager_test

production:
  <<: *default
  port: 5432
  host: <%= ENV['DB_URL'] %>
  database: <%= ENV['DB_NAME'] %>
  username: <%= ENV['DB_USERNAME'] %>
  password: <%= ENV["DB_PASSWORD"] %>
